version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: users
    ports:
      - "5432:5432"
      - "9229:9229"
  
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
    ports:
      - "3333:3333"
    depends_on:
      - postgres